export interface DasTraderFill {
  Symbol: string;
  'Time/Date': string;
  FillType: string;
  Side: string;
  Price: number;
  Quantity: number;
  TIF: string;
  'Account Type': string;
  Account: string;
  ExchangeName: string;
  'Route/Ref': string;
  'Order #': string;
  'Fill ID': string;
  Commission: number;
  'Net Amount': number;
  'Clearing Account': string;
  'Clearing Account ID': string;
  'CMTA': string;
  'CMTA ID': string;
  'Give Up': string;
  'Give Up ID': string;
  'Exec Trader': string;
  'Sleeve': string;
  'Avg Price': number;
  'Position': number;
  'Open P&L': number;
  'Closed P&L': number;
  'Mark Price': number;
  'Mark Value': number;
  'Unrealized P&L': number;
  'Realized P&L': number;
  'Total P&L': number;
  'Net P&L': number;
  'Margin Req': number;
  'Buying Power': number;
  'Equity': number;
  'Equity Excess': number;
  'Margin Excess': number;
  'Short Excess': number;
  'Cash Balance': number;
  'Pending Cash': number;
  'Pending Shares': number;
  'Pending Orders': number;
  'Net Shares': number;
  'Net Value': number;
  'Commission Today': number;
  'Commission Total': number;
  'Shares Today': number;
  'Shares Total': number;
  'Trades Today': number;
  'Trades Total': number;
  'Volume Today': number;
  'Volume Total': number;
  'Turnover Today': number;
  'Turnover Total': number;
  'High Today': number;
  'Low Today': number;
  'Open Price': number;
  'Close Price': number;
  'VWAP': number;
  'Bid': number;
  'Ask': number;
  'Last': number;
  'Change': number;
  'Change %': number;
  'Volume': number;
  'Open Interest': number;
  'Implied Vol': number;
  'Delta': number;
  'Gamma': number;
  'Theta': number;
  'Vega': number;
  'Rho': number;
  'Beta': number;
  'Correlation': number;
  'Volatility': number;
  'Historical Vol': number;
  'IV Rank': number;
  'IV Percentile': number;
  'Strike': number;
  'Expiration': string;
  'DTE': number;
  ContractType: string;
  'Underlying': string;
  'Multiplier': number;
  'Currency': string;
  'ContractExchange': string;
  'Primary Exchange': string;
  'Category': string;
  'Subcategory': string;
  'Industry': string;
  'Sector': string;
  'Description': string;
  'Local Symbol': string;
  'Conid': number;
  'Security ID': string;
  'CUSIP': string;
  'ISIN': string;
  'SEDOL': string;
  'RIC': string;
  'Bloomberg': string;
  'Reuters': string;
  'Yahoo': string;
  'Google': string;
  'Quandl': string;
  'Alpha Vantage': string;
  'IEX Cloud': string;
  'Polygon.io': string;
  'Tradier': string;
  'TD Ameritrade': string;
  'E*TRADE': string;
  'Interactive Brokers': string;
  'Charles Schwab': string;
  'Fidelity': string;
  'Robinhood': string;
  'Webull': string;
  'M1 Finance': string;
  'Public': string;
  'SoFi': string;
  'Ally': string;
  'Vanguard': string;
  'Betterment': string;
  'Wealthfront': string;
  'Personal Capital': string;
  'Mint': string;
  'YNAB': string;
  'Quicken': string;
  'TurboTax': string;
  'Credit Karma': string;
  'Experian': string;
  'TransUnion': string;
  'Equifax': string;
  'FICO': string;
  'VantageScore': string;
  'Credit Score': number;
  'Credit Limit': number;
  'Credit Utilization': number;
  'Available Credit': number;
  'Current Balance': number;
  'Minimum Payment': number;
  'APR': number;
  'Interest Rate': number;
  'Annual Fee': number;
  'Late Payment Fee': number;
  'Cash Advance Fee': number;
  'Balance Transfer Fee': number;
  'Foreign Transaction Fee': number;
  'Overdraft Fee': number;
  'Returned Payment Fee': number;
  'Stop Payment Fee': number;
  'Wire Transfer Fee': number;
  'Cashier Check Fee': number;
  'Money Order Fee': number;
  'Notary Fee': number;
  'Safe Deposit Box Fee': number;
  'Account Maintenance Fee': number;
  'Paper Statement Fee': number;
  'Inactivity Fee': number;
  'Closure Fee': number;
  'Early Termination Fee': number;
  'NSF Fee': number;
  'Overdraft Protection Fee': number;
}

export interface ProcessedFill {
  symbol: string;
  price: number;
  quantity: number;
  side: 'BUY' | 'SELL';
  timestamp: Date;
  commission: number;
}

export interface Trade {
  id: string;
  symbol: string;
  status: 'OPEN' | 'CLOSED';
  openDate: Date;
  closeDate?: Date;
  openPrice: number;
  closePrice?: number;
  quantity: number;
  side: 'BUY' | 'SELL';
  pnl?: number;
  commission: number;
  createdAt: Date;
  updatedAt: Date;
  fills: ProcessedFill[];
}
